trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:

- template: templates/build-node.yml
  parameters:
    nodeVersion: '20'
    runTests: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    pathToPublish: 'dist'
    artifactName: 'drop'